
spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/bank
    username: bank_user
    password: bank_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:tc:postgresql:latest:///bank_test
    username: test
    password:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false